from typing import Protocol

from PIL import Image

type ImageBuffer = bytearray | list[int]


class EPDDisplay(Protocol):
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

    def init(self): ...
    def init_part(self): ...
    def init_fast(self) -> None: ...
    def init_4Gray(self) -> None: ...
    def getbuffer(self, image: Image.Image) -> ImageBuffer: ...
    def getbuffer_4Gray(self, image: Image.Image) -> ImageBuffer: ...
    def display(self, image: ImageBuffer) -> None: ...
    def display_Partial(
        self, buffer: ImageBuffer, Xstart: int, Ystart: int, Xend: int, Yend: int
    ) -> None: ...
    def Clear(self) -> None: ...
    def display_4Gray(self, image: Image.Image) -> None: ...
    def sleep(self) -> None: ...
