from typing import Literal, Protocol

from PIL import Image

type ImageBuffer = bytearray | list[int]


class EPDDisplay(Protocol):
    width: int
    height: int

    def init(self) -> None | Literal[-1, 0]: ...
    def init_part(self) -> None | Literal[-1, 0]: ...
    def init_fast(self) -> None | Literal[-1, 0]: ...
    def init_4Gray(self) -> None | Literal[-1, 0]: ...
    def getbuffer(self, image: Image.Image) -> ImageBuffer: ...
    def getbuffer_4Gray(self, image: Image.Image) -> ImageBuffer: ...
    def display(self, image: ImageBuffer) -> None: ...
    def display_Partial(
        self, Image: ImageBuffer, Xstart: int, Ystart: int, Xend: int, Yend: int
    ) -> None: ...
    def Clear(self) -> None: ...
    def display_4Gray(self, image: Image.Image) -> None: ...
    def sleep(self) -> None: ...
